import fs from 'fs';
import path from 'path';
import vm from 'vm';
import { createRequire } from 'module';
import ts from 'typescript';

const require = createRequire(import.meta.url);
const root = process.cwd();
const sourcePath = path.join(root, 'data', 'studySeed.ts');
const outputPath = path.join(root, 'supabase', 'study_content_setup.sql');

const source = fs.readFileSync(sourcePath, 'utf8');
const compiled = ts.transpileModule(source, {
  compilerOptions: {
    module: ts.ModuleKind.CommonJS,
    target: ts.ScriptTarget.ES2020,
  },
}).outputText;

const module = { exports: {} };
const sandbox = { exports: module.exports, module, require, console };
vm.runInNewContext(compiled, sandbox, { filename: 'studySeed.js' });
const exported = module.exports;
const { studyQuestions = [] } = exported;

const escape = (value) => {
  if (value === null || value === undefined) return 'null';
  return `'${String(value).replace(/'/g, "''")}'`;
};

const json = (value) => `${escape(JSON.stringify(value))}::jsonb`;
const slugify = (value) => String(value)
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/(^-|-$)/g, '');

const subjectMap = new Map();
const topicMap = new Map();

studyQuestions.forEach((question, index) => {
  if (!subjectMap.has(question.subject)) {
    subjectMap.set(question.subject, {
      id: slugify(question.subject),
      name: question.subject,
      sort_order: subjectMap.size + 1,
    });
  }

  const topicKey = `${question.subject}::${question.topic}`;
  if (!topicMap.has(topicKey)) {
    topicMap.set(topicKey, {
      id: slugify(`${question.subject}-${question.topic}`),
      subject_id: subjectMap.get(question.subject).id,
      name: question.topic,
      sort_order: Array.from(topicMap.values()).filter((item) => item.subject_id === subjectMap.get(question.subject).id).length + 1,
    });
  }

  question.sort_order = index + 1;
});

const subjects = Array.from(subjectMap.values());
const topics = Array.from(topicMap.values());

const lines = [];
lines.push('-- Generated by scripts/generateStudyContentSql.mjs');
lines.push('create extension if not exists pgcrypto;');
lines.push('');
lines.push('create table if not exists public.study_subjects (');
lines.push('  id text primary key,');
lines.push('  name text not null unique,');
lines.push('  slug text not null unique,');
lines.push('  sort_order integer not null default 0,');
lines.push('  created_at timestamptz not null default now()');
lines.push(');');
lines.push('');
lines.push('create table if not exists public.study_topics (');
lines.push('  id text primary key,');
lines.push('  subject_id text not null references public.study_subjects(id) on delete cascade,');
lines.push('  name text not null,');
lines.push('  slug text not null,');
lines.push('  sort_order integer not null default 0,');
lines.push('  created_at timestamptz not null default now(),');
lines.push('  unique (subject_id, name),');
lines.push('  unique (subject_id, slug)');
lines.push(');');
lines.push('');
lines.push('create table if not exists public.study_questions (');
lines.push('  id integer primary key,');
lines.push('  subject_id text not null references public.study_subjects(id) on delete restrict,');
lines.push('  topic_id text not null references public.study_topics(id) on delete restrict,');
lines.push("  level text not null check (level in ('Fácil', 'Médio', 'Difícil')), ");
lines.push('  statement text not null,');
lines.push('  options jsonb not null,');
lines.push('  correct_index integer not null,');
lines.push('  explanation text not null,');
lines.push('  sort_order integer not null default 0,');
lines.push('  created_at timestamptz not null default now()');
lines.push(');');
lines.push('');
lines.push('create index if not exists idx_study_topics_subject_id on public.study_topics(subject_id, sort_order);');
lines.push('create index if not exists idx_study_questions_subject_id on public.study_questions(subject_id, sort_order);');
lines.push('create index if not exists idx_study_questions_topic_id on public.study_questions(topic_id, sort_order);');
lines.push('');
lines.push('alter table public.study_subjects enable row level security;');
lines.push('alter table public.study_topics enable row level security;');
lines.push('alter table public.study_questions enable row level security;');
lines.push('');
lines.push('grant usage on schema public to anon, authenticated;');
lines.push('grant select on public.study_subjects to anon, authenticated;');
lines.push('grant select on public.study_topics to anon, authenticated;');
lines.push('grant select on public.study_questions to anon, authenticated;');
lines.push('');
lines.push('drop policy if exists "public read study subjects" on public.study_subjects;');
lines.push('create policy "public read study subjects" on public.study_subjects for select to anon, authenticated using (true);');
lines.push('drop policy if exists "public read study topics" on public.study_topics;');
lines.push('create policy "public read study topics" on public.study_topics for select to anon, authenticated using (true);');
lines.push('drop policy if exists "public read study questions" on public.study_questions;');
lines.push('create policy "public read study questions" on public.study_questions for select to anon, authenticated using (true);');
lines.push('');
lines.push('insert into public.study_subjects (id, name, slug, sort_order) values');
lines.push(subjects.map((subject) => `  (${escape(subject.id)}, ${escape(subject.name)}, ${escape(slugify(subject.name))}, ${subject.sort_order})`).join(',\n'));
lines.push('on conflict (id) do update set name = excluded.name, slug = excluded.slug, sort_order = excluded.sort_order;');
lines.push('');
lines.push('insert into public.study_topics (id, subject_id, name, slug, sort_order) values');
lines.push(topics.map((topic) => `  (${escape(topic.id)}, ${escape(topic.subject_id)}, ${escape(topic.name)}, ${escape(slugify(topic.name))}, ${topic.sort_order})`).join(',\n'));
lines.push('on conflict (id) do update set subject_id = excluded.subject_id, name = excluded.name, slug = excluded.slug, sort_order = excluded.sort_order;');
lines.push('');
lines.push('insert into public.study_questions (id, subject_id, topic_id, level, statement, options, correct_index, explanation, sort_order) values');
lines.push(studyQuestions.map((question) => {
  const subjectId = subjectMap.get(question.subject).id;
  const topicId = topicMap.get(`${question.subject}::${question.topic}`).id;
  return `  (${question.id}, ${escape(subjectId)}, ${escape(topicId)}, ${escape(question.level)}, ${escape(question.statement)}, ${json(question.options)}, ${question.correctIndex}, ${escape(question.explanation)}, ${question.sort_order})`;
}).join(',\n'));
lines.push('on conflict (id) do update set subject_id = excluded.subject_id, topic_id = excluded.topic_id, level = excluded.level, statement = excluded.statement, options = excluded.options, correct_index = excluded.correct_index, explanation = excluded.explanation, sort_order = excluded.sort_order;');

fs.writeFileSync(outputPath, `${lines.join('\n')}\n`);
console.log(`Generated ${outputPath} with ${subjects.length} subjects, ${topics.length} topics and ${studyQuestions.length} questions.`);
